import type {Field,RecordItem} from "@/components/dashboard/operations-page";
export type OperationConfig={resource:string;title:string;description:string;actionLabel:string;fields:Field[];columns:string[];seed:RecordItem[]};
const f=(key:string,label:string,type:Field["type"]="text",options?:string[]):Field=>({key,label,type,options});
const status=(...x:string[])=>f("status","Status","select",x);
export const operations:Record<string,OperationConfig>={
alunos:{resource:"students",title:"Alunos",description:"Gerencie cadastros, perfis e o histórico dos seus alunos.",actionLabel:"Novo aluno",fields:[f("name","Nome"),f("email","E-mail","email"),f("phone","Telefone"),f("plan","Plano","select",["Mensal","Premium","Anual"]),status("Ativo","Inativo")],columns:["name","email","phone","plan","status"],seed:[{id:"1",name:"Mariana Silva",email:"mariana@email.com",phone:"(11) 99911-2200",plan:"Premium",status:"Ativo"},{id:"2",name:"Lucas Santos",email:"lucas@email.com",phone:"(11) 98822-1100",plan:"Mensal",status:"Ativo"},{id:"3",name:"Camila Oliveira",email:"camila@email.com",phone:"(11) 97733-4400",plan:"Anual",status:"Inativo"}]},
planos:{resource:"plans",title:"Planos",description:"Configure modalidades, benefícios, valores e recorrências.",actionLabel:"Novo plano",fields:[f("name","Nome"),f("price","Valor"),f("period","Recorrência","select",["Mensal","Trimestral","Anual"]),f("students","Alunos","number"),status("Ativo","Inativo")],columns:["name","price","period","students","status"],seed:[{id:"1",name:"Essencial",price:"R$ 99,90",period:"Mensal",students:"142",status:"Ativo"},{id:"2",name:"Premium",price:"R$ 149,90",period:"Mensal",students:"198",status:"Ativo"},{id:"3",name:"Performance",price:"R$ 1.299,00",period:"Anual",students:"88",status:"Ativo"}]},
matriculas:{resource:"enrollments",title:"Matrículas",description:"Acompanhe vínculos, vencimentos e renovações de contratos.",actionLabel:"Nova matrícula",fields:[f("name","Aluno"),f("plan","Plano","select",["Mensal","Premium","Anual"]),f("start","Início","date"),f("end","Vencimento","date"),status("Vigente","Pendente","Encerrada")],columns:["name","plan","start","end","status"],seed:[{id:"1",name:"Mariana Silva",plan:"Premium",start:"01/08/2026",end:"31/08/2026",status:"Vigente"},{id:"2",name:"Lucas Santos",plan:"Mensal",start:"10/08/2026",end:"09/09/2026",status:"Vigente"},{id:"3",name:"Bruna Lima",plan:"Anual",start:"15/08/2025",end:"14/08/2026",status:"Pendente"}]},
pagamentos:{resource:"payments",title:"Pagamentos",description:"Visualize receitas, cobranças e pendências financeiras.",actionLabel:"Registrar pagamento",fields:[f("name","Aluno"),f("value","Valor"),f("method","Método","select",["Pix","Cartão","Boleto","Dinheiro"]),f("date","Data","date"),status("Pago","Pendente","Cancelado")],columns:["name","value","method","date","status"],seed:[{id:"1",name:"Ana Beatriz",value:"R$ 149,90",method:"Pix",date:"29/08/2026",status:"Pago"},{id:"2",name:"Felipe Martins",value:"R$ 119,90",method:"Cartão",date:"28/08/2026",status:"Pago"},{id:"3",name:"Bruna Lima",value:"R$ 189,90",method:"Boleto",date:"27/08/2026",status:"Pendente"}]},
checkin:{resource:"checkins",title:"Check-in",description:"Registre acessos e acompanhe a movimentação da academia.",actionLabel:"Realizar check-in",fields:[f("name","Aluno"),f("plan","Plano","select",["Mensal","Premium","Anual"]),f("date","Data","date"),f("time","Horário"),status("Liberado","Bloqueado")],columns:["name","plan","date","time","status"],seed:[{id:"1",name:"Mariana Silva",plan:"Premium",date:"29/08/2026",time:"18:42",status:"Liberado"},{id:"2",name:"Lucas Santos",plan:"Mensal",date:"29/08/2026",time:"18:39",status:"Liberado"},{id:"3",name:"Camila Oliveira",plan:"Anual",date:"29/08/2026",time:"18:35",status:"Bloqueado"}]}}
