create extension if not exists pgcrypto;
create type user_role as enum ('owner','admin','instructor','student','superadmin');
create type subscription_status as enum ('trialing','active','past_due','paused','cancelled');
create table tenants(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table users(id uuid primary key default gen_random_uuid(),tenant_id uuid references tenants(id) on delete cascade,email text not null,password_hash text not null,full_name text not null,role user_role not null,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,email));
create unique index users_superadmin_email_key on users(lower(email)) where tenant_id is null;
create table sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,token_hash text not null unique,expires_at timestamptz not null,ip_hash text,user_agent text,created_at timestamptz not null default now());
create index sessions_user_id_idx on sessions(user_id);create index sessions_expires_at_idx on sessions(expires_at);
create table students(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants(id) on delete cascade,user_id uuid references users(id) on delete set null,full_name text not null,email text,phone text,document text,birth_date date,height_cm numeric(5,2),weight_kg numeric(6,2),goal text,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,document));
create index students_tenant_id_idx on students(tenant_id);
create table plans(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants(id) on delete cascade,name text not null,amount_cents integer not null check(amount_cents>0),currency char(3) not null default 'BRL',billing_cycle text not null check(billing_cycle in('monthly','quarterly','yearly')),stripe_price_id text,active boolean not null default true,created_at timestamptz not null default now());
create table subscriptions(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants(id) on delete cascade,student_id uuid not null references students(id),plan_id uuid not null references plans(id),provider text not null,provider_customer_id text,provider_subscription_id text unique,status subscription_status not null default 'trialing',current_period_end timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index subscriptions_tenant_idx on subscriptions(tenant_id);
create table payments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants(id) on delete cascade,subscription_id uuid references subscriptions(id),provider text not null,provider_payment_id text unique,amount_cents integer not null,currency char(3) not null default 'BRL',status text not null,payment_method text,paid_at timestamptz,created_at timestamptz not null default now());
create table webhook_events(id uuid primary key default gen_random_uuid(),provider text not null,provider_event_id text not null,status text not null default 'received',payload jsonb not null,processed_at timestamptz,created_at timestamptz not null default now(),unique(provider,provider_event_id));
create table audit_logs(id bigserial primary key,tenant_id uuid references tenants(id),actor_user_id uuid references users(id),action text not null,entity text not null,entity_id text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
-- The service-role is used only by the backend. Deny direct anonymous access by default.
alter table tenants enable row level security;alter table users enable row level security;alter table sessions enable row level security;alter table students enable row level security;alter table plans enable row level security;alter table subscriptions enable row level security;alter table payments enable row level security;alter table webhook_events enable row level security;alter table audit_logs enable row level security;
create table auth_attempts(id bigserial primary key,email text not null,ip_hash text not null,successful boolean not null,created_at timestamptz not null default now());create index auth_attempts_lookup_idx on auth_attempts(email,ip_hash,created_at);alter table auth_attempts enable row level security;
