import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {requireUser} from "@/server/auth/session";
import {db} from "@/server/db/client";
import {apiError} from "@/server/http";

const text=z.string().trim().min(1).max(180);
const schemas={
 students:z.object({name:text,email:z.string().email(),phone:z.string().max(30),plan:text,status:z.enum(["Ativo","Inativo"])}),
 plans:z.object({name:text,price:text,period:z.enum(["Mensal","Trimestral","Anual"]),students:z.string(),status:z.enum(["Ativo","Inativo"])}),
 enrollments:z.object({name:text,plan:text,start:z.string().date(),end:z.string().date(),status:z.enum(["Vigente","Pendente","Encerrada"])}),
 payments:z.object({name:text,value:text,method:z.enum(["Pix","Cartão","Boleto","Dinheiro"]),date:z.string().date(),status:z.enum(["Pago","Pendente","Cancelado"])}),
 checkins:z.object({name:text,plan:text,date:z.string().date(),time:z.string().regex(/^\d{2}:\d{2}$/),status:z.enum(["Liberado","Bloqueado"])})
};
type Resource=keyof typeof schemas;type Row=Record<string,unknown>;
const resources=new Set(Object.keys(schemas));
const money=(value:string)=>{const normalized=value.replace(/[^\d,.-]/g,"").replace(/\./g,"").replace(",", ".");const cents=Math.round(Number(normalized)*100);if(!Number.isFinite(cents)||cents<=0)throw new Error("Valor monetário inválido");return cents};
const currency=(cents:unknown)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(cents)/100);
function serialize(resource:Resource,row:Row){switch(resource){case"students":return{id:String(row.id),name:String(row.full_name),email:String(row.email??""),phone:String(row.phone??""),plan:String(row.plan_name??"Sem plano"),status:String(row.status)};case"plans":return{id:String(row.id),name:String(row.name),price:currency(row.amount_cents),period:({monthly:"Mensal",quarterly:"Trimestral",yearly:"Anual"} as Record<string,string>)[String(row.billing_cycle)]??String(row.billing_cycle),students:"—",status:row.active?"Ativo":"Inativo"};case"enrollments":return{id:String(row.id),name:String(row.student_name),plan:String(row.plan_name),start:String(row.start_date),end:String(row.end_date),status:String(row.status)};case"payments":return{id:String(row.id),name:String(row.payer_name??"Pagamento manual"),value:currency(row.amount_cents),method:String(row.payment_method??"Manual"),date:String(row.paid_at??row.created_at).slice(0,10),status:String(row.status)};case"checkins":return{id:String(row.id),name:String(row.student_name),plan:String(row.plan_name),date:String(row.checkin_date),time:String(row.checkin_time).slice(0,5),status:String(row.status)}}}
function insertData(resource:Resource,input:Record<string,string>,tenantId:string){switch(resource){case"students":return{tenant_id:tenantId,full_name:input.name,email:input.email,phone:input.phone,plan_name:input.plan,status:input.status};case"plans":return{tenant_id:tenantId,name:input.name,amount_cents:money(input.price),billing_cycle:({Mensal:"monthly",Trimestral:"quarterly",Anual:"yearly"} as Record<string,string>)[input.period],active:input.status==="Ativo"};case"enrollments":return{tenant_id:tenantId,student_name:input.name,plan_name:input.plan,start_date:input.start,end_date:input.end,status:input.status};case"payments":return{tenant_id:tenantId,provider:"manual",provider_payment_id:`manual_${crypto.randomUUID()}`,payer_name:input.name,amount_cents:money(input.value),status:input.status,payment_method:input.method,paid_at:input.date};case"checkins":return{tenant_id:tenantId,student_name:input.name,plan_name:input.plan,checkin_date:input.date,checkin_time:input.time,status:input.status}}}
export async function GET(_:NextRequest,{params}:{params:Promise<{resource:string}>}){try{const user=await requireUser(["owner","admin","instructor"]);if(!user.tenant_id)throw new Error("Tenant ausente");const {resource:raw}=await params;if(!resources.has(raw))return NextResponse.json({error:"Recurso inválido"},{status:404});const resource=raw as Resource;const table=resource;const rows=await db.select<Row>(table,{select:"*",tenant_id:`eq.${user.tenant_id}`,order:"created_at.desc",limit:200});return NextResponse.json({data:rows.map(row=>serialize(resource,row))})}catch(error){return apiError(error)}}
export async function POST(request:NextRequest,{params}:{params:Promise<{resource:string}>}){try{const user=await requireUser(["owner","admin"]);if(!user.tenant_id)throw new Error("Tenant ausente");const {resource:raw}=await params;if(!resources.has(raw))return NextResponse.json({error:"Recurso inválido"},{status:404});const resource=raw as Resource;const input=schemas[resource].parse(await request.json()) as Record<string,string>;const [row]=await db.insert<Row>(resource,insertData(resource,input,user.tenant_id));await db.insert("audit_logs",{tenant_id:user.tenant_id,actor_user_id:user.id,action:`${resource}.create`,entity:resource,entity_id:String(row.id)});return NextResponse.json({data:serialize(resource,row)},{status:201})}catch(error){return apiError(error)}}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{resource:string}>}){try{const user=await requireUser(["owner","admin"]);if(!user.tenant_id)throw new Error("Tenant ausente");const {resource:raw}=await params;const id=z.string().uuid().parse(request.nextUrl.searchParams.get("id"));if(!resources.has(raw))return NextResponse.json({error:"Recurso inválido"},{status:404});if(raw==="payments")return NextResponse.json({error:"Pagamentos não podem ser excluídos; use cancelamento ou estorno."},{status:409});await db.remove(raw,{id:`eq.${id}`,tenant_id:`eq.${user.tenant_id}`});await db.insert("audit_logs",{tenant_id:user.tenant_id,actor_user_id:user.id,action:`${raw}.delete`,entity:raw,entity_id:id});return new NextResponse(null,{status:204})}catch(error){return apiError(error)}}
