import {randomBytes,scrypt as scryptCallback} from "node:crypto";import {promisify} from "node:util";
const scrypt=promisify(scryptCallback);const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configure SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY");
async function hash(password){const salt=randomBytes(16),derived=await scrypt(password,salt,64);return `scrypt:${salt.toString("hex")}:${derived.toString("hex")}`}
async function api(table,{method="GET",query="",data}={}){const response=await fetch(`${url}/rest/v1/${table}${query?`?${query}`:""}`,{method,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=representation"},body:data?JSON.stringify(data):undefined});if(!response.ok)throw new Error(`${table}: ${await response.text()}`);return response.status===204?[]:response.json()}
const password=process.env.SEED_OWNER_PASSWORD;if(!password||password.length<12)throw new Error("SEED_OWNER_PASSWORD deve ter pelo menos 12 caracteres");const slug="academia-performance";
let [tenant]=await api("tenants",{query:`select=id,name&slug=eq.${slug}&limit=1`});if(!tenant)[tenant]=await api("tenants",{method:"POST",data:{name:process.env.SEED_TENANT_NAME||"Academia Performance",slug}});
const passwordHash=await hash(password);const wanted=[{email:(process.env.SEED_OWNER_EMAIL||"admin@gymflow.com").toLowerCase(),full_name:"Proprietário",role:"owner",tenant_id:tenant.id},{email:"instrutor@gymflow.com",full_name:"Instrutor",role:"instructor",tenant_id:tenant.id},{email:"aluno@gymflow.com",full_name:"Aluno",role:"student",tenant_id:tenant.id},{email:"superadmin@gymflow.com",full_name:"Superadmin",role:"superadmin",tenant_id:null}];
for(const user of wanted){const tenantFilter=user.tenant_id?`&tenant_id=eq.${user.tenant_id}`:"&tenant_id=is.null";const existing=await api("users",{query:`select=id&email=eq.${encodeURIComponent(user.email)}${tenantFilter}&limit=1`});if(!existing.length)await api("users",{method:"POST",data:{...user,password_hash:passwordHash,active:true}})}
const students=await api("students",{query:`select=id&tenant_id=eq.${tenant.id}&limit=1`});if(!students.length)await api("students",{method:"POST",data:[{tenant_id:tenant.id,full_name:"Mariana Silva",email:"mariana@email.com",phone:"(11) 99911-2200",plan_name:"Premium",status:"Ativo",height_cm:165,weight_kg:68},{tenant_id:tenant.id,full_name:"Lucas Santos",email:"lucas@email.com",phone:"(11) 98822-1100",plan_name:"Mensal",status:"Ativo"}]});
const plans=await api("plans",{query:`select=id&tenant_id=eq.${tenant.id}&limit=1`});if(!plans.length)await api("plans",{method:"POST",data:[{tenant_id:tenant.id,name:"Mensal",amount_cents:9990,billing_cycle:"monthly",active:true},{tenant_id:tenant.id,name:"Premium",amount_cents:14990,billing_cycle:"monthly",active:true},{tenant_id:tenant.id,name:"Anual",amount_cents:129900,billing_cycle:"yearly",active:true}]});
const settings=await api("tenant_settings",{query:`select=tenant_id&tenant_id=eq.${tenant.id}&limit=1`});if(!settings.length)await api("tenant_settings",{method:"POST",data:{tenant_id:tenant.id,legal_name:tenant.name,unit_name:"Unidade Centro",timezone:"America/Sao_Paulo",currency:"BRL",payment_reminders:true}});
console.log(`Seed concluído para ${slug}: usuários, alunos, planos e configurações.`);
